// runs the bundled connector over stdio and prints a transcript. needs make bundle
import { Client } from "../node_modules/@modelcontextprotocol/sdk/dist/esm/client/index.js";
import { StdioClientTransport } from "../node_modules/@modelcontextprotocol/sdk/dist/esm/client/stdio.js";
import { resolve } from "node:path";

import { spawn } from "node:child_process";
import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const root = resolve(import.meta.dirname, "..");
const env = process.env.MERIDIAN_ENV ?? "prod";
const port = 18000 + Math.floor(Math.random() * 1000);
const url = `http://127.0.0.1:${port}`;

// own service + fresh db so old state cant leak into the transcript
const service = spawn("npx", ["tsx", "src/service/main.ts", "serve", "--port", String(port)], {
  cwd: root, stdio: "ignore", detached: true,
  env: { ...process.env, MERIDIAN_ENV: env, MERIDIAN_DB: join(mkdtempSync(join(tmpdir(), "demo-")), "demo.sqlite") },
});
const stop = () => { try { process.kill(-service.pid); } catch {} };
process.on("exit", stop);
for (let i = 0; ; i++) {
  try { if ((await fetch(`${url}/health`)).ok) break; } catch {}
  if (i > 100) { console.error("service did not start"); process.exit(1); }
  await new Promise((r) => setTimeout(r, 200));
}

async function session(user, steps) {
  const t = new StdioClientTransport({
    command: "node", args: [`${root}/bundle/server.mjs`], stderr: "ignore",
    env: { PATH: process.env.PATH, MERIDIAN_ENV: env, MERIDIAN_USER: user, MERIDIAN_SERVICE_URL: url,
      MERIDIAN_PERMISSIONS: `${root}/dist/${env}/permissions.json`, MERIDIAN_DIRECTORY: `${root}/data/directory` },
  });
  const c = new Client({ name: "demo", version: "0" });
  await c.connect(t);
  await c.listTools(); // hosts do this first
  console.log(`\n### Server started as \`${user}\` (${env})\n`);
  for (const [label, name, args] of steps) {
    const r = await c.callTool({ name, arguments: args });
    console.log(`**${label}**\n\n\`\`\`\n> ${name}(${JSON.stringify(args)})\n${r.isError ? "[isError] " : ""}${JSON.stringify(JSON.parse(r.content[0].text), null, 2).slice(0, 900)}\n\`\`\`\n`);
  }
  await c.close();
}

console.log(`# Transcript: Meridian usage connector (${env})\n\nGenerated by \`node scripts/demo.mjs\` over real stdio against the built bundle and the live service.`);
await session("priya.nair@meridianls.example", [
  ["1. Allowed read: team lead, own group (default)", "usage_summary", { period: "2026-08" }],
  ["2. Denied read: team lead asks for another group", "usage_summary", { group: "finance", period: "2026-08" }],
  ["3. Denied write: team lead tries to switch off web-search", "set_capability", { group: "clinical-operations", capability: "web-search", enabled: false }],
  ["4. Still unchanged afterwards", "capability_status", {}],
]);
await session("sofia.rossi@meridianls.example", [
  ["5. Denied: usage-connector is disabled for Finance in prod", "usage_summary", { period: "2026-08" }],
]);
await session("chloe.dubois@meridianls.example", [
  ["6. Allowed: platform admin reads another group", "top_users", { group: "finance", period: "2026-08", limit: 3 }],
  ["7. Allowed: platform admin enables the connector for Finance", "set_capability", { group: "finance", capability: "usage-connector", enabled: true }],
]);
await session("sofia.rossi@meridianls.example", [
  ["8. Finance lead now allowed (own group only)", "usage_summary", { period: "2026-08" }],
  ["9. ...but still denied for HR", "usage_summary", { group: "hr", period: "2026-08" }],
]);
stop();
